---
title: "Class06_homework"
author: "Fan Wu(PID:A15127541)"
format: pdf
---

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

>Q6. How would you generalize the original code above to work with any set of input protein structures?

```{r}
# input: in PDB format, any protein that contains a chain A and has alpha carbon atoms.
plot_chainA_Bfactor <- function(x){
  library(bio3d)
  protein_structure <- read.pdb(x)
  protein_structure.chainA <- trim.pdb(protein_structure, 
                                       chain="A", elety="CA")
  protein_structure.b <- protein_structure.chainA$atom$b
  plotb3(protein_structure.b, sse=protein_structure.chainA, 
         typ="l", ylab="Bfactor")
}
#output: a graph of the flexibility of chain A's backbone in the input protein structure
```

Outputs of the fucntion `plot_chainA_Bfactor()` can be compared to that of original code

```{r}
# demo1 of the function, can be compared to original code
plot_chainA_Bfactor ("4AKE")
```

```{r}
# demo2 of the function, can be compared to original code
plot_chainA_Bfactor ("1AKE")
```

```{r}
# demo3 of the function, can be compared to original code
plot_chainA_Bfactor ("1E4Y")
```

